### PR TITLE
Add show confimation dialogs with custom widget

### PR DESCRIPTION
**Pull request by ThibNach**
please check https://github.com/TheEmidee/UEGameBaseFramework/pull/243 for the entire feature

Add the possibility to use specific widget instead of the common one for confirmation dialogs.

I've chosen to modify the existing methods instead of creating overloads because at the end. It was resulting that in `UAsyncAction_ShowConfirmation::Activate()` I had to check if `CustomDialogWidget` is nullptr or not to call the old or the new `ShowConfirmation()` method ( for the olds node still working). 
And since calling the old method, called the new one with the Common widget as parameter, I m thinking that this way the code is more readable and understandable avoiding overloads

- - -
This change is [Reviewable](https://reviewable.io/reviews/TheEmidee/UECommonGame/1)

### CODE REVIEW

**Review by Frickerson — DISMISSED** [review]

**Review by TheEmidee — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UECommonGame/1)* status: all files reviewed, 2 unresolved discussions (waiting on @ThibNach)

___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 26 at r1](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NsiF2zQAXw8Q8rmU7hS:-NsiF2zQAXw8Q8rmU7hT:b-qjupbc) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/81ca5cb0f2e156c8696e64f4e96cbb23c6d70bf0/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L26)):*
> ```cpp
> UAsyncAction_ShowConfirmation * UAsyncAction_ShowConfirmation::ShowConfirmationWithCustomWidgetYesNo( UObject * in_world_context_object, FText title, FText message, TSubclassOf< UCommonGameDialog > custom_dialog_widget )
> {
>     UAsyncAction_ShowConfirmation * action = NewObject< UAsyncAction_ShowConfirmation >();
> ```

lots of common code in this file. Can you keep one version of the code in a private helper function? 
___
*[`Source/Private/Messaging/CommonMessagingSubsystem.cpp` line 3 at r1](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NsiEunG9UNng8qdW1k1:-NsiEunG9UNng8qdW1k2:bcxh3xr) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/81ca5cb0f2e156c8696e64f4e96cbb23c6d70bf0/Source/Private/Messaging/CommonMessagingSubsystem.cpp#L3)):*
> ```cpp
> #include "Messaging/CommonMessagingSubsystem.h"
> 
> #include "Messaging/CommonGameDialog.h"
> ```

isn't it possible to use a forward declaration?

**Review by ThibNach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UECommonGame/1)* status: all files reviewed, 2 unresolved discussions (waiting on @TheEmidee)

___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 26 at r1](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NsiF2zQAXw8Q8rmU7hS:-NsliLChAtddc9QGU3sX:b-896fix) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/81ca5cb0f2e156c8696e64f4e96cbb23c6d70bf0/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L26)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

lots of common code in this file. Can you keep one version of the code in a private helper function?
</blockquote></details>

Done.
___
*[`Source/Private/Messaging/CommonMessagingSubsystem.cpp` line 3 at r1](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NsiEunG9UNng8qdW1k1:-NslcT3A7daTwFgDwoD4:b-896fix) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/81ca5cb0f2e156c8696e64f4e96cbb23c6d70bf0/Source/Private/Messaging/CommonMessagingSubsystem.cpp#L3)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

isn't it possible to use a forward declaration?
</blockquote></details>

Done.

**Review by Frickerson — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UECommonGame/1)* status: all files reviewed, 10 unresolved discussions (waiting on @TheEmidee and @ThibNach)

___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 1 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzLKOAvOddLqCXw3H:-NslzLKOAvOddLqCXw3I:byp18fd) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L1)):*
> ```cpp
> // Copyright Epic Games, Inc. All Rights Reserved.
> ```

Remove
___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 5 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzMhP7X2yWqPVFAgY:-NslzMhP7X2yWqPVFAgZ:b32vk7) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L5)):*
> ```cpp
> #include "Actions/AsyncAction_ShowConfirmation.h"
> 
> #include "Engine/GameInstance.h"
> ```

<>
___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 9 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzZE54NuZqf3BpztI:-NslzZE54NuZqf3BpztJ:b-fkwnl5) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L9)):*
> ```cpp
> #include "Messaging/CommonMessagingSubsystem.h"
> 
> UAsyncAction_ShowConfirmation::UAsyncAction_ShowConfirmation( const FObjectInitializer & ObjectInitializer ) :
> ```

Function parameters: lower_snake_case
For all the functions in this file
___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 67 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzkCKCrsc7_gpSG8G:-NslzkCKCrsc7_gpSG8H:bsfh5eq) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L67)):*
> ```cpp
>     if ( TargetLocalPlayer )
>     {
>         if ( UCommonMessagingSubsystem * Messaging = TargetLocalPlayer->GetSubsystem< UCommonMessagingSubsystem >() )
> ```

auto * messaging
___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 69 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-Nslzm_c-4bMDEieYr9-:-Nslzm_c-4bMDEieYr90:b54d5q3) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L69)):*
> ```cpp
>         if ( UCommonMessagingSubsystem * Messaging = TargetLocalPlayer->GetSubsystem< UCommonMessagingSubsystem >() )
>         {
>             FCommonMessagingResultDelegate ResultCallback = FCommonMessagingResultDelegate::CreateUObject( this, &UAsyncAction_ShowConfirmation::HandleConfirmationResult );
> ```

auto result_callback
___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 90 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzpHk8jxgeCMg9o2U:-NslzpHk8jxgeCMg9o2V:b-ieu4yw) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L90)):*
> ```cpp
> UAsyncAction_ShowConfirmation * UAsyncAction_ShowConfirmation::CreateAction( UObject * in_world_context, UCommonGameDialogDescriptor * descriptor, TSubclassOf< UCommonGameDialog > custom_dialog_widget )
> {
>     UAsyncAction_ShowConfirmation * action = NewObject< UAsyncAction_ShowConfirmation >();
> ```

auto * action
___
*[`Source/Public/Actions/AsyncAction_ShowConfirmation.h` line 1 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzrJ_9G_XELBdEG-5:-NslzrJ_9G_XELBdEG-6:byp18fd) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Public/Actions/AsyncAction_ShowConfirmation.h#L1)):*
> ```objc
> // Copyright Epic Games, Inc. All Rights Reserved.
> ```

Remove
___
*[`Source/Public/Actions/AsyncAction_ShowConfirmation.h` line 5 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzsBH2xL0ggYx5t1W:-NslzsBH2xL0ggYx5t1X:b-y3lipd) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Public/Actions/AsyncAction_ShowConfirmation.h#L5)):*
> ```objc
> #pragma once
> 
> #include "Kismet/BlueprintAsyncActionBase.h"
> ```

<> and below

**Review by ThibNach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UECommonGame/1)* status: all files reviewed, 10 unresolved discussions (waiting on @TheEmidee and @VectorGamez)

___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 1 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzLKOAvOddLqCXw3H:-Nsm2DRz6LtFNQFw1ZC9:b-896fix) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L1)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 5 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzMhP7X2yWqPVFAgY:-Nsm2FoOEObwdpSNvMiz:b-896fix) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L5)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

<>
</blockquote></details>

Done.
___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 9 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzZE54NuZqf3BpztI:-Nsm5zdU6QvIXRvDADRu:b-896fix) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L9)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

Function parameters: lower_snake_case
For all the functions in this file
</blockquote></details>

Done.
___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 67 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzkCKCrsc7_gpSG8G:-Nsm6ERbCePZtOR3alRn:b-896fix) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L67)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

auto * messaging
</blockquote></details>

Done.
___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 69 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-Nslzm_c-4bMDEieYr9-:-Nsm6Gd7CnNdWkXV_4iQ:b-896fix) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L69)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

auto result_callback
</blockquote></details>

Done.
___
*[`Source/Private/Actions/AsyncAction_ShowConfirmation.cpp` line 90 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzpHk8jxgeCMg9o2U:-Nsm6Je737W6-xoVjKEU:b-896fix) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Private/Actions/AsyncAction_ShowConfirmation.cpp#L90)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

auto * action
</blockquote></details>

Done.
___
*[`Source/Public/Actions/AsyncAction_ShowConfirmation.h` line 1 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzrJ_9G_XELBdEG-5:-Nsm6SeX3OcU-kH3j4ML:b-896fix) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Public/Actions/AsyncAction_ShowConfirmation.h#L1)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`Source/Public/Actions/AsyncAction_ShowConfirmation.h` line 5 at r2](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-NslzsBH2xL0ggYx5t1W:-Nsm6Tcb22EMNiIICV64:b-896fix) ([raw file](https://github.com/TheEmidee/UECommonGame/blob/13c4a87d61c8c0e66a31deeb7cd2c777c35dd9d1/Source/Public/Actions/AsyncAction_ShowConfirmation.h#L5)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

<> and below
</blockquote></details>

Done.

**Review by Frickerson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-:-NsmSMf6DmMvkXYOK_Pa:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @TheEmidee)

**Review by TheEmidee — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UECommonGame/1#-:-Nsn88gvD9b1afHYu4Tq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ThibNach)

**Pull request merged**
